version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: repan
      POSTGRES_PASSWORD: repan_dev
      POSTGRES_DB: repan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
